[package]
name = "reciept"
authors = [""]
compiler_version = ">=0.18.0"
type = "contract"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.16.4", directory="yarn-project/aztec-nr/aztec" }
safe_math = { git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.16.4", directory="yarn-project/aztec-nr/safe-math"}
authwit={ git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.16.4", directory="yarn-project/aztec-nr/authwit"}
token={ git="https://github.com/AztecProtocol/aztec-packages/", tag="aztec-packages-v0.16.4", directory="yarn-project/noir-contracts/src/contracts/token_contract"}

